# FIX [The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0] warnning log
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end